name: CWChat
main: net.clashwars.cwchat.bukkit.CWChatPlugin
version: 1.0
author: clashwars
description: Chat system
commands:
  cwchat:
    description: Reload configurations
    usage: /<command>
  a:
    description: Admin chat
    usage: /<command> [message]
    aliases: [s]
  g:
    description: Group chat command
    aliases: [group, group, gr]
    usage: /<command> help