name: CWChat
main: net.clashwars.cwchat.bukkit.CWChatPlugin
version: 1.0
author: clashwars
description: Chat system
commands:
  cwchat:
    description: Reload configurations
    usage: /<command>
  list:
    description: Displays people in certain groups
    aliases: [who, players, playerlist]
    usage: /<command> [all]
    aliases: [staff, online]
  a:
    description: Admin chat
    usage: /<command> [message]
    aliases: [s]
  g:
    description: Group chat command
    aliases: [group, group, gr]
    usage: /<command> help
  msg:
    description: Send a private message to a player
    aliases: [message, tell]
    usage: /<command> <player> <msg>