main : com.clashwars.cwchat.CWChat
name: CWChat
version: 1.0
description: Chat formatting and utilities.
commands:
  cwchat:
    description: Reload configurations
    usage: /<command>
  a:
    description: Admin chat
    usage: /<command> [message]
    aliases: [s]
  g:
    description: Group chat command
    aliases: [group, group, gr]
    usage: /<command> help